apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    path: alloy
    repoURL: https://projects.corybuecker.dev/corybuecker/git-ops.git
    targetRevision: HEAD
  destination:
    namespace: alloy
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true