apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        fsGroup: 473
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 473
        runAsNonRoot: true
        runAsUser: 473
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: alloy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          image: alloy
          resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
          volumeMounts:
          - name: data
            mountPath: /var/lib/alloy/data
          - name: tmp
            mountPath: /tmp
          - name: config
            mountPath: /etc/alloy
          - name: proc
            mountPath: /host/proc
          - name: sys
            mountPath: /host/sys
            readOnly: true
          imagePullPolicy: IfNotPresent
      volumes:
      - name: tmp
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: alloy
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys