apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      securityContext:
        fsGroup: 473
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 473
        runAsNonRoot: true
        runAsUser: 473
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: alloy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          image: alloy
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - name: data
            mountPath: /var/lib/alloy/data
          - name: tmp
            mountPath: /tmp
          - name: config
            mountPath: /etc/alloy
          imagePullPolicy: IfNotPresent
      volumes:
      - name: tmp
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: alloy