apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - sealedsecret.json
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml

images:
  - name: forgejo
    newName: codeberg.org/forgejo/forgejo
    newTag: 16.0.5-rootless
    digest: sha256:5effb7305584aca479b29fde6f9631a6dbe86ae798ae02eeea33a3666f0c0bf8

configMapGenerator:
  - name: forgejo
    envs:
      - conf/forgejo.env